// Sheet → LaTeX document. Each math block becomes an `equation*`; text
// blocks become plain paragraphs. The output is a self-contained
// `\documentclass{article}` source the user can paste into Overleaf.

import type { Sheet } from '../state/types';

export function sheetToLatex(sheet: Sheet): string {
  const out: string[] = [];
  out.push(
    '% Generated by Math Notebook',
    '\\documentclass[11pt]{article}',
    '\\usepackage{amsmath,amssymb,amsthm}',
    '\\usepackage[T1]{fontenc}',
    '\\usepackage[utf8]{inputenc}',
    '\\usepackage{lmodern}',
    '\\usepackage{geometry}\\geometry{margin=1in}',
    '',
    `\\title{${escapeLatex(sheet.name)}}`,
    '\\author{}',
    '\\date{}',
    '',
    '\\begin{document}',
    '\\maketitle',
    '',
  );
  for (const b of sheet.blocks) {
    if (b.type === 'math') {
      out.push('\\begin{equation*}', b.latex, '\\end{equation*}');
      if (b.note) out.push(`% ${escapeLatex(b.note)}`);
    } else {
      out.push(escapeLatex(b.text || ''), '');
    }
  }
  if (sheet.notes && sheet.notes.trim()) {
    out.push('', '\\section*{Notes}', '', escapeLatex(sheet.notes));
  }
  out.push('', '\\end{document}', '');
  return out.join('\n');
}

function escapeLatex(s: string): string {
  return s
    .replace(/\\/g, '\\textbackslash{}')
    .replace(/([&%$#_{}])/g, '\\$1')
    .replace(/~/g, '\\textasciitilde{}')
    .replace(/\^/g, '\\textasciicircum{}');
}
